name: Validate Kubernetes Setup

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  validate-setup:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Ansible
      run: |
        sudo apt-get update
        sudo apt-get install -y ansible
    
    - name: Validate Ansible Playbooks
      run: |
        ansible-playbook --syntax-check kubernetes-setup/master-playbook.yml
        ansible-playbook --syntax-check kubernetes-setup/node-playbook.yml
        ansible-playbook --syntax-check CKS/hands-on/vagrant/main.yml
    
    - name: Check Vagrant Configuration
      run: |
        # Install Vagrant for validation
        wget -O- https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
        echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
        sudo apt-get update && sudo apt-get install -y vagrant
        
        # Basic Vagrantfile syntax validation (without provider checks)
        echo "Checking main Vagrantfile syntax..."
        ruby -c Vagrantfile || (echo "Main Vagrantfile has syntax errors" && exit 1)
        
        echo "Checking CKS Vagrantfile syntax..."
        cd CKS/hands-on/vagrant
        ruby -c Vagrantfile || (echo "CKS Vagrantfile has syntax errors" && exit 1)
        
        echo "All Vagrantfile syntax checks passed"
    
    - name: Run Setup Validation
      run: |
        chmod +x validate.sh
        ./validate.sh --setup-only --skip-vagrant
    
    - name: Check Test Scripts
      run: |
        chmod +x tests/*.sh
        # Basic syntax check for test scripts
        bash -n tests/test_cluster.sh
        bash -n tests/test_networking.sh
        bash -n tests/test_storage.sh
        bash -n tests/test_services.sh